# Generated by Django 4.1.3 on 2023-12-01 07:28

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=600)),
                ('sentences', models.JSONField()),
                ('image', models.ImageField(upload_to='about_images/')),
                ('display_on_screen', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(help_text='Web Development', max_length=50)),
                ('JobDetail', models.CharField(help_text='Permanent | Islamabad | Software / IT Engineer', max_length=150)),
                ('JobStatus', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('JobDescription', models.TextField(help_text='Short Job Description')),
                ('JobDescriptionImage', models.ImageField(max_length=200, upload_to='career/')),
                ('Responsibilities', models.TextField(default="['a', 'b']")),
                ('ResponsibilitiesImage', models.ImageField(max_length=200, upload_to='career/')),
                ('Requirements', models.TextField(default="['a', 'b']")),
                ('MinimumExperience', models.CharField(help_text='1 Year', max_length=50)),
                ('JobCategory', models.CharField(help_text='Web Developer', max_length=50)),
                ('Department', models.CharField(help_text='Backend Development', max_length=50)),
                ('JobType', models.CharField(help_text='Permanent', max_length=50)),
                ('Location', models.CharField(help_text='Comsats University Sahiwal', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', tinymce.models.HTMLField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='null', max_length=50)),
                ('phone', models.CharField(default='null', max_length=50)),
                ('profileimage', models.ImageField(blank=True, max_length=200, null=True, upload_to='customers/')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataUtilizationStrategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=600)),
                ('Image', models.ImageField(upload_to='DataUtilization/')),
                ('display_on_screen', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', tinymce.models.HTMLField()),
                ('display_on_screen', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurCore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='MISSION, VISION, AND VALUES', max_length=50)),
                ('MissionTitle', models.CharField(default='Our Mission', max_length=100)),
                ('MissionImage', models.ImageField(upload_to='OurCore/')),
                ('MissionContent', models.TextField(max_length=400)),
                ('VisionTitle', models.CharField(default='Our Vision', max_length=100)),
                ('VisionImage', models.ImageField(upload_to='OurCore/')),
                ('VisionContent', models.TextField(max_length=400)),
                ('ValuesTitle', models.CharField(default='Our Values', max_length=100)),
                ('ValuesImage', models.ImageField(upload_to='OurCore/')),
                ('ValuesContent', models.JSONField()),
                ('display_on_screen', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Content', models.TextField(max_length=600)),
                ('Image', models.ImageField(upload_to='OurCulture/')),
                ('display_on_screen', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_filter', models.CharField(choices=[('filter-Business', 'Business Intelligence'), ('filter-Research', 'Research Consultancy'), ('filter-AI', 'Artificial Intelligence')], max_length=50)),
                ('Image_Title', models.CharField(help_text='Enter your image Title', max_length=50)),
                ('portfolio_Image', models.ImageField(max_length=200, upload_to='portfolio/')),
            ],
        ),
        migrations.CreateModel(
            name='projectmanagers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('profileimage', models.ImageField(blank=True, max_length=200, null=True, upload_to='projectmanagers/')),
                ('about', tinymce.models.HTMLField()),
                ('company', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('TwitterProfile', models.URLField()),
                ('FacebookProfile', models.URLField()),
                ('InstagramProfile', models.URLField()),
                ('LinkedinProfile', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('Comments', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=50)),
                ('service_desc', models.TextField()),
                ('serviceimage', models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to='services/')),
                ('servicedetail_desc', tinymce.models.HTMLField(default='no data')),
                ('image_desc', models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to='servicedetails/')),
                ('Sited_Services_title', models.CharField(default='no data', max_length=50)),
                ('Sited_Services', tinymce.models.HTMLField(default='no data')),
                ('image_Sited_Services', models.ImageField(blank=True, default=None, max_length=200, null=True, upload_to='servicedetails/')),
                ('title_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='service_title', unique=True)),
                ('display_on_screen', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('description', models.TextField(max_length=500)),
                ('Site_url', models.URLField(blank=True, null=True)),
                ('display_on_screen', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatSetsUsApart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='WhatSetsUsApart/')),
                ('description', models.TextField(max_length=430)),
                ('display_on_screen', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whatwedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon_image', models.ImageField(upload_to='Whatwedo_icons/')),
                ('description', models.TextField(max_length=280)),
                ('display_on_screen', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='requestform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetype', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('project_title', models.CharField(max_length=50)),
                ('requirementfile', models.FileField(blank=True, default=None, max_length=200, null=True, upload_to='requirement_Doc/')),
                ('Project_Budget', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Project_Start_Date', models.DateField(blank=True, null=True)),
                ('Project_Finnish_Date', models.DateField(blank=True, null=True)),
                ('ShortDesc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Rejected', 'Rejected'), ('Accepted', 'Accepted'), ('Pending', 'Pending')], default='Pending', max_length=200, null=True)),
                ('projectstatus', models.CharField(choices=[('Delivered', 'Delivered'), ('In Progress', 'In Progress'), ('Complete', 'Complete')], default='In Progress', max_length=200, null=True)),
                ('paymentstatus', models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'Unpaid')], default='Unpaid', max_length=200, null=True)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_projects', to='customer.projectmanagers')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCompletionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='completion_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customer.requestform')),
            ],
        ),
        migrations.CreateModel(
            name='portfolioDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(help_text='Enter Project Category', max_length=50)),
                ('Client', models.CharField(max_length=50)),
                ('Projectdate', models.DateField()),
                ('ProjectURL', models.URLField(default='www.example.com')),
                ('Description', models.TextField(default='Write portfolio Details', help_text='Portfolio Details')),
                ('projectImage', models.ImageField(max_length=200, upload_to='portfolioDetails/')),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='CareerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=12)),
                ('About', models.TextField()),
                ('CV', models.FileField(max_length=200, upload_to='jobcv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('RequestStatus', models.CharField(choices=[('In Process', 'In Process'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='In Process', max_length=12)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('JobTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='customer.career')),
            ],
        ),
    ]
