# Generated by Django 4.1.3 on 2023-12-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Sited_Services',
            field=models.JSONField(),
        ),
    ]
