# Generated by Django 4.1.3 on 2023-12-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_services_sited_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='Sited_Services',
            new_name='SitedServices',
        ),
    ]
