# Generated by Django 4.1.3 on 2023-12-02 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_services_servicedetail_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.services'),
        ),
    ]
