# Generated by Django 4.1.3 on 2023-12-02 16:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_requestform_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='requirementfile',
            field=models.FileField(max_length=200, upload_to='requirement_Doc/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.services'),
        ),
    ]
