# Generated by Django 4.1.3 on 2023-12-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_requestform_requirementfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
