# Generated by Django 4.1.3 on 2023-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Office Equipment', 'Office Equipment'), ('Other', 'Other')], default='Hardware', max_length=20)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.FloatField()),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
