# Generated by Django 4.1.3 on 2023-12-01 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', tinymce.models.HTMLField(blank=True, null=True)),
                ('team_type', models.CharField(choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Business Analyst', 'Business Analyst'), ('QA Engineer', 'QA Engineer'), ('DEVOPS', 'DEVOPS')], default='Developer', max_length=200, null=True)),
                ('profileimage', models.ImageField(blank=True, max_length=200, null=True, upload_to='team/')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('TwitterProfile', models.URLField(default='https://web.facebook.com/?_rdc=1&_rdr')),
                ('FacebookProfile', models.URLField(default='https://web.facebook.com/?_rdc=1&_rdr')),
                ('InstagramProfile', models.URLField(default='https://web.facebook.com/?_rdc=1&_rdr')),
                ('LinkedinProfile', models.URLField(default='https://web.facebook.com/?_rdc=1&_rdr')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.projectmanagers')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_status', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.requestform')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects_team', to='projectmanager.team')),
            ],
        ),
    ]
