# Generated by Django 4.1.3 on 2023-12-01 07:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
                ('projectmanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendancelist', to='customer.projectmanagers')),
            ],
        ),
    ]
